### ISSUE TITLE
Изменить расширения файлов .cpp на .c

### ISSUE THREAD

**Issue by koshkinHSE** [HSE-Warriors/HeckingCompiler#1]
Предлагаю изменить расширение этого и следующих файлов на .c для корректного отображения языка
@KovshefulCoder @Shish-ok

**Comment by KovshefulCoder** [comment]
Я думаю, что это как-то слишком запарно. И вообще, это не поломает файлы?

**Comment by koshkinHSE** [comment]
Не должно

**Comment by KovshefulCoder** [comment]
Тогда сделаем

**Comment by KovshefulCoder** [comment]
Думаю лучше сделать это финальным штришком, чтобы если все же не будет работать, то финальная версия была и в обычных cpp файлах

**Comment by koshkinHSE** [comment]
Готово
