### ISSUE TITLE
Протестировать свои части

### ISSUE THREAD

**Issue by KovshefulCoder** [HSE-Warriors/HeckingCompiler#5]
После выполнения своей части оттестируете свою часть кода, исправьте баги
После этого и готовности к merge с общей веткой main отпишите сюда в комментарии

**Comment by KovshefulCoder** [comment]
К merge c master готов, приступаю

**Comment by Shish-ok** [comment]
Добавил главную форматирующую функцию, готово к слиянию

**Comment by koshkinHSE** [comment]
Всё закончено и протестировано, можно мерджить
